name: 'Disconnect Action'
description: 'Disconnect a Parasoft Service Virtualization server'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  ctpUrl:
    required: true
    description: 'CTP URL'
  ctpUsername:
    required: true
    description: 'CTP Username'
  ctpPassword:
    required: true
    description: 'CTP Password'
  serverMatch:
    required: true
    description: 'Used to specify server by host or name'
  server:
    required: true
    description: 'Host or name of the server'
runs:
  using: 'node12'
  main: 'dist/index.js'
